//
//  ExchangeRatesRouter.swift
//  PayPayCurrency
//
//  Created by Fachri Febrian on 15/08/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ExchangeRatesRoutingLogic {
    func routeToCountryCurrencies(segue: UIStoryboardSegue?)
}

protocol ExchangeRatesDataPassing {
    var dataStore: ExchangeRatesDataStore? { get }
}

class ExchangeRatesRouter: NSObject, ExchangeRatesRoutingLogic, ExchangeRatesDataPassing {
    weak var viewController: ExchangeRatesViewController?
    var dataStore: ExchangeRatesDataStore?
    
    // MARK: Routing
    
    func routeToCountryCurrencies(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! CountryCurrencyViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "CountryCurrencyViewController") as! CountryCurrencyViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
            navigateToSomewhere(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    func navigateToSomewhere(source: ExchangeRatesViewController,
                             destination: CountryCurrencyViewController
    ) {
        source.navigationController?.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToSomewhere(source: ExchangeRatesDataStore,
                             destination: inout CountryCurrencyDataStore) {
        
    }
}
