//
//  ExchangeRatesPresenter.swift
//  PayPayCurrency
//
//  Created by Fachri Febrian on 15/08/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ExchangeRatesPresentationLogic {
    func presentFromCurrency(response: ExchangeRates.PickCurrency.Response)
    func presentLatestConversionRate(response: ExchangeRates.LatestRate.Response)
}

class ExchangeRatesPresenter: ExchangeRatesPresentationLogic {
    weak var viewController: ExchangeRatesDisplayLogic?
    
    // MARK: Present rates conversion rate
    
    func presentFromCurrency(response: ExchangeRates.PickCurrency.Response) {
        let viewModel = ExchangeRates.PickCurrency.ViewModel(currency: response.currency)
        viewController?.displayFromCurrency(viewModel: viewModel)
    }
    
    func presentLatestConversionRate(response: ExchangeRates.LatestRate.Response) {
        let sortedRates = response.rates.sorted { $0.key < $1.key }
        let rates = sortedRates.map { key, value in
            return ExchangeRates.LatestRate.ViewModel.DisplayedRate(name: key, amount: value)
        }
        
        let viewModel = ExchangeRates.LatestRate.ViewModel(rates: rates)
        viewController?.displayLatestConversionRate(viewModel: viewModel)
    }
    
}
