//
//  ExchangeRatesModels.swift
//  PayPayCurrency
//
//  Created by Fachri Febrian on 15/08/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ExchangeRates {
    // MARK: Use cases
    
    enum LatestRate {
        
        struct Request {
            var value: Double = 1.0
            var currency = Currency(currency: "USD", country: "United States Dollar")
        }
        
        struct Response {
            var rates: [String: Double]
            var currency: Currency?
        }
        
        struct ViewModel {
            struct DisplayedRate {
                var name: String
                var amount: Double
            }
            var rates: [DisplayedRate]
            var currency: Currency?
        }
    }
    
    enum PickCurrency {
        
        struct Request {
            
        }
        
        struct Response {
            var currency: Currency?
        }
        
        struct ViewModel {
            var currency: Currency?
        }
    }
}
