//
//  CountryCurrencyWorker.swift
//  PayPayCurrency
//
//  Created by Fachri Febrian on 15/08/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CountryCurrencyWorker {
    let cacheDataSource: CurrenciesCacheDataSource
    let apiDataSource: CurrenciesApiDataSource
    
    init(cacheDataSource: CurrenciesCacheDataSource = CurrenciesCacheDataSource(userDefaults: UserDefaults.standard),
         apiDataSource: CurrenciesApiDataSource = CurrenciesApiDataSource(service: Service.shared)) {
        self.cacheDataSource = cacheDataSource
        self.apiDataSource = apiDataSource
    }
    
    func fetchCurrencies(completion: @escaping ([String : String]) -> Void) {
        let currencies = cacheDataSource.fetchCurrencies()
        if !Service.isConnectedToNetwork() {
            DispatchQueue.main.async {
                completion(currencies)
            }
        } else {
            if (!currencies.isEmpty) {
                apiDataSource.fetchCurrencies { [weak self] currencies in
                    if (!currencies.isEmpty) {
                        self?.cacheDataSource.createCurrencies(currencies: currencies)
                    }
                }
                DispatchQueue.main.async {
                    completion(currencies)
                }
            } else {
                apiDataSource.fetchCurrencies { [weak self] currencies in
                    self?.cacheDataSource.createCurrencies(currencies: currencies)
                    DispatchQueue.main.async {
                        completion(currencies)
                    }
                }
            }
        }
    }
}
