//
//  CountryCurrencyInteractor.swift
//  PayPayCurrency
//
//  Created by Fachri Febrian on 15/08/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CountryCurrencyBusinessLogic {
    func fetchCurrencies(request: CountryCurrency.Currencies.Request)
}

protocol CountryCurrencyDataStore {
    var currencies: [Currency] { get }
}

class CountryCurrencyInteractor: CountryCurrencyBusinessLogic, CountryCurrencyDataStore {
    var presenter: CountryCurrencyPresentationLogic?
    var worker = CountryCurrencyWorker()
    var currencies: [Currency] = []
    
    // MARK: Fetch Currencies
    
    func fetchCurrencies(request: CountryCurrency.Currencies.Request) {
        worker.fetchCurrencies { [weak self] curencies in
            let countryCurrencies = curencies.map({
                return Currency(currency: $0.key, country: $0.value)
            })
            
            let response = CountryCurrency.Currencies.Response(currencies: countryCurrencies)
            self?.presenter?.presentCurrencies(response: response)
        }
    }
}
