//
//  CountryCurrencyPresenter.swift
//  PayPayCurrency
//
//  Created by Fachri Febrian on 15/08/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CountryCurrencyPresentationLogic {
    func presentCurrencies(response: CountryCurrency.Currencies.Response)
}

class CountryCurrencyPresenter: CountryCurrencyPresentationLogic {
    weak var viewController: CountryCurrencyDisplayLogic?
    
    // MARK: Do something
    
    func presentCurrencies(response: CountryCurrency.Currencies.Response) {
        let sortedCurrencies = response.currencies.sorted { $0.currency < $1.currency }
        
        let viewModel = CountryCurrency.Currencies.ViewModel(currencies: sortedCurrencies)
        viewController?.displayCurrencies(viewModel: viewModel)
    }
}
