//
//  CountryCurrencyRouter.swift
//  PayPayCurrency
//
//  Created by Fachri Febrian on 15/08/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CountryCurrencyRoutingLogic {
    func popViewController(segue: UIStoryboardSegue?)
}

protocol CountryCurrencyDataPassing {
    var dataStore: CountryCurrencyDataStore? { get }
}

class CountryCurrencyRouter: NSObject, CountryCurrencyRoutingLogic, CountryCurrencyDataPassing {
    weak var viewController: CountryCurrencyViewController?
    var dataStore: CountryCurrencyDataStore?
    
    // MARK: Routing
    
    func popViewController(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! ExchangeRatesViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        } else {
            let index = viewController!.navigationController!.viewControllers.count - 2
            let destinationVC = viewController?.navigationController?.viewControllers[index] as! ExchangeRatesViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
            navigateToSomewhere(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    func navigateToSomewhere(source: CountryCurrencyViewController, destination: ExchangeRatesViewController) {
        source.navigationController?.popViewController(animated: true)
    }
    
    // MARK: Passing data
    
    func passDataToSomewhere(source: CountryCurrencyDataStore, destination: inout ExchangeRatesDataStore) {
        destination.currency = viewController?.currency
    }
}
